var searchData=
[
  ['rawinstallablescommand_0',['RawInstallablesCommand',['../structnix_1_1RawInstallablesCommand.html',1,'nix']]],
  ['readconn_1',['ReadConn',['../structnix_1_1CommonProto_1_1ReadConn.html',1,'nix::CommonProto::ReadConn'],['../structnix_1_1ServeProto_1_1ReadConn.html',1,'nix::ServeProto::ReadConn'],['../structnix_1_1WorkerProto_1_1ReadConn.html',1,'nix::WorkerProto::ReadConn']]],
  ['readlinelikeinteracter_2',['ReadlineLikeInteracter',['../classnix_1_1ReadlineLikeInteracter.html',1,'nix']]],
  ['realisation_3',['Realisation',['../structnix_1_1Realisation.html',1,'nix']]],
  ['realisedpath_4',['RealisedPath',['../structnix_1_1RealisedPath.html',1,'nix']]],
  ['receiveinterrupts_5',['ReceiveInterrupts',['../structnix_1_1ReceiveInterrupts.html',1,'nix']]],
  ['reconstructvisitor_6',['ReconstructVisitor',['../structnix_1_1parseAsync_1_1ReconstructVisitor.html',1,'nix::parseAsync']]],
  ['recursionhelper_7',['RecursionHelper',['../structnix_1_1charptr__cast__detail_1_1RecursionHelper.html',1,'nix::charptr_cast_detail']]],
  ['recursionhelper_3c_20from_2c_20to_2c_20std_3a_3aenable_5fif_5ft_3c_20basecase_3c_20from_2c_20to_20_3e_20_3e_20_3e_8',['RecursionHelper&lt; From, To, std::enable_if_t&lt; BaseCase&lt; From, To &gt; &gt; &gt;',['../structnix_1_1charptr__cast__detail_1_1RecursionHelper_3_01From_00_01To_00_01std_1_1enable__if__tceffa6d1841b8b6692043232e4814a0f.html',1,'nix::charptr_cast_detail']]],
  ['recursionhelper_3c_20from_2c_20to_2c_20std_3a_3aenable_5fif_5ft_3c_20std_3a_3ais_5fpointer_5fv_3c_20from_20_3e_20_26_26std_3a_3ais_5fpointer_5fv_3c_20to_20_3e_20_26_26validqualifiers_3c_20from_2c_20to_20_3e_20_3e_20_3e_9',['RecursionHelper&lt; From, To, std::enable_if_t&lt; std::is_pointer_v&lt; From &gt; &amp;&amp;std::is_pointer_v&lt; To &gt; &amp;&amp;ValidQualifiers&lt; From, To &gt; &gt; &gt;',['../structnix_1_1charptr__cast__detail_1_1RecursionHelper_3_01From_00_01To_00_01std_1_1enable__if__t40624b81bb334dff6fe3df9e43dcb989.html',1,'nix::charptr_cast_detail']]],
  ['recursionhelper_3c_20std_3a_3aremove_5fpointer_5ft_3c_20from_20_3e_2c_20std_3a_3aremove_5fpointer_5ft_3c_20to_20_3e_20_3e_10',['RecursionHelper&lt; std::remove_pointer_t&lt; From &gt;, std::remove_pointer_t&lt; To &gt; &gt;',['../structnix_1_1charptr__cast__detail_1_1RecursionHelper.html',1,'nix::charptr_cast_detail']]],
  ['ref_11',['ref',['../classnix_1_1ref.html',1,'nix']]],
  ['ref_3c_20nix_3a_3aeval_5fcache_3a_3acachingevaluator_20_3e_12',['ref&lt; nix::eval_cache::CachingEvaluator &gt;',['../classnix_1_1ref.html',1,'nix']]],
  ['ref_3c_20nix_3a_3aeval_5fcache_3a_3aevalcache_20_3e_13',['ref&lt; nix::eval_cache::EvalCache &gt;',['../classnix_1_1ref.html',1,'nix']]],
  ['ref_3c_20nix_3a_3aexpr_20_3e_14',['ref&lt; nix::Expr &gt;',['../classnix_1_1ref.html',1,'nix']]],
  ['ref_3c_20nix_3a_3aextrapathinfo_20_3e_15',['ref&lt; nix::ExtraPathInfo &gt;',['../classnix_1_1ref.html',1,'nix']]],
  ['ref_3c_20nix_3a_3aflake_3a_3anode_20_3e_16',['ref&lt; nix::flake::Node &gt;',['../classnix_1_1ref.html',1,'nix']]],
  ['ref_3c_20nix_3a_3alocalfsstore_20_3e_17',['ref&lt; nix::LocalFSStore &gt;',['../classnix_1_1ref.html',1,'nix']]],
  ['ref_3c_20nix_3a_3alocalstore_20_3e_18',['ref&lt; nix::LocalStore &gt;',['../classnix_1_1ref.html',1,'nix']]],
  ['ref_3c_20nix_3a_3apool_3c_20nix_3a_3alegacysshstore_3a_3aconnection_20_3e_20_3e_19',['ref&lt; nix::Pool&lt; nix::LegacySSHStore::Connection &gt; &gt;',['../classnix_1_1ref.html',1,'nix']]],
  ['ref_3c_20nix_3a_3apool_3c_20nix_3a_3aremotestore_3a_3aconnection_20_3e_20_3e_20',['ref&lt; nix::Pool&lt; nix::RemoteStore::Connection &gt; &gt;',['../classnix_1_1ref.html',1,'nix']]],
  ['ref_3c_20nix_3a_3asinglebuiltpath_20_3e_21',['ref&lt; nix::SingleBuiltPath &gt;',['../classnix_1_1ref.html',1,'nix']]],
  ['ref_3c_20nix_3a_3asinglederivedpath_20_3e_22',['ref&lt; nix::SingleDerivedPath &gt;',['../classnix_1_1ref.html',1,'nix']]],
  ['ref_3c_20nix_3a_3astore_20_3e_23',['ref&lt; nix::Store &gt;',['../classnix_1_1ref.html',1,'nix']]],
  ['ref_3c_20std_3a_3astring_20_3e_24',['ref&lt; std::string &gt;',['../classnix_1_1ref.html',1,'nix']]],
  ['refscansink_25',['RefScanSink',['../classnix_1_1RefScanSink.html',1,'nix']]],
  ['regex_26',['Regex',['../structnix_1_1Regex.html',1,'nix']]],
  ['regexcache_27',['RegexCache',['../structnix_1_1RegexCache.html',1,'nix']]],
  ['regexpattern_28',['RegexPattern',['../structnix_1_1MixProfileElementMatchers_1_1RegexPattern.html',1,'nix::MixProfileElementMatchers']]],
  ['register_29',['Register',['../structnix_1_1GlobalConfig_1_1Register.html',1,'nix::GlobalConfig']]],
  ['registerprimop_30',['RegisterPrimOp',['../structnix_1_1RegisterPrimOp.html',1,'nix']]],
  ['registry_31',['Registry',['../structnix_1_1fetchers_1_1Registry.html',1,'nix::fetchers']]],
  ['registrycommand_32',['RegistryCommand',['../classnix_1_1RegistryCommand.html',1,'nix']]],
  ['remotefsaccessor_33',['RemoteFSAccessor',['../classnix_1_1RemoteFSAccessor.html',1,'nix']]],
  ['remotestore_34',['RemoteStore',['../classnix_1_1RemoteStore.html',1,'nix']]],
  ['remotestoreconfig_35',['RemoteStoreConfig',['../structnix_1_1RemoteStoreConfig.html',1,'nix']]],
  ['replcompletermixin_36',['ReplCompleterMixin',['../structnix_1_1detail_1_1ReplCompleterMixin.html',1,'nix::detail']]],
  ['replinteracter_37',['ReplInteracter',['../classnix_1_1ReplInteracter.html',1,'nix']]],
  ['restrictedstore_38',['RestrictedStore',['../structnix_1_1RestrictedStore.html',1,'nix']]],
  ['restrictedstoreconfig_39',['RestrictedStoreConfig',['../structnix_1_1RestrictedStoreConfig.html',1,'nix']]],
  ['result_40',['Result',['../classnix_1_1checked_1_1Checked_1_1Result.html',1,'nix::checked::Checked']]],
  ['results_41',['Results',['../structnix_1_1Worker_1_1Results.html',1,'nix::Worker']]],
  ['rewriteparams_42',['RewriteParams',['../structnix_1_1RewriteParams.html',1,'nix']]],
  ['rewriter_43',['Rewriter',['../classnix_1_1Rewriter.html',1,'nix']]],
  ['rewritetest_44',['RewriteTest',['../classnix_1_1RewriteTest.html',1,'nix']]],
  ['rewritingsource_45',['RewritingSource',['../structnix_1_1RewritingSource.html',1,'nix']]],
  ['runningprogram_46',['RunningProgram',['../structnix_1_1RunningProgram.html',1,'nix']]],
  ['runoptions_47',['RunOptions',['../structnix_1_1RunOptions.html',1,'nix']]],
  ['runpager_48',['RunPager',['../classnix_1_1RunPager.html',1,'nix']]]
];
