var searchData=
[
  ['s3binarycachestore_0',['S3BinaryCacheStore',['../classnix_1_1S3BinaryCacheStore.html',1,'nix']]],
  ['searchpath_1',['SearchPath',['../structnix_1_1SearchPath.html',1,'nix']]],
  ['secretkey_2',['SecretKey',['../structnix_1_1SecretKey.html',1,'nix']]],
  ['serialise_3',['Serialise',['../structnix_1_1CommonProto_1_1Serialise.html',1,'nix::CommonProto::Serialise&lt; T &gt;'],['../structnix_1_1ServeProto_1_1Serialise.html',1,'nix::ServeProto::Serialise&lt; T &gt;'],['../structnix_1_1WorkerProto_1_1Serialise.html',1,'nix::WorkerProto::Serialise&lt; T &gt;']]],
  ['serialise_3c_20buildresult_20_3e_4',['Serialise&lt; BuildResult &gt;',['../structnix_1_1ServeProto_1_1Serialise_3_01BuildResult_01_4.html',1,'nix::ServeProto::Serialise&lt; BuildResult &gt;'],['../structnix_1_1WorkerProto_1_1Serialise_3_01BuildResult_01_4.html',1,'nix::WorkerProto::Serialise&lt; BuildResult &gt;']]],
  ['serialise_3c_20contentaddress_20_3e_5',['Serialise&lt; ContentAddress &gt;',['../structnix_1_1CommonProto_1_1Serialise_3_01ContentAddress_01_4.html',1,'nix::CommonProto']]],
  ['serialise_3c_20derivedpath_20_3e_6',['Serialise&lt; DerivedPath &gt;',['../structnix_1_1WorkerProto_1_1Serialise_3_01DerivedPath_01_4.html',1,'nix::WorkerProto']]],
  ['serialise_3c_20drvoutput_20_3e_7',['Serialise&lt; DrvOutput &gt;',['../structnix_1_1CommonProto_1_1Serialise_3_01DrvOutput_01_4.html',1,'nix::CommonProto']]],
  ['serialise_3c_20keyedbuildresult_20_3e_8',['Serialise&lt; KeyedBuildResult &gt;',['../structnix_1_1WorkerProto_1_1Serialise_3_01KeyedBuildResult_01_4.html',1,'nix::WorkerProto']]],
  ['serialise_3c_20realisation_20_3e_9',['Serialise&lt; Realisation &gt;',['../structnix_1_1CommonProto_1_1Serialise_3_01Realisation_01_4.html',1,'nix::CommonProto']]],
  ['serialise_3c_20std_3a_3amap_3c_20k_20comma_5f_20v_20_3e_20_3e_10',['Serialise&lt; std::map&lt; K COMMA_ V &gt; &gt;',['../structnix_1_1CommonProto_1_1Serialise_3_01std_1_1map_3_01K_01COMMA___01V_01_4_01_4.html',1,'nix::CommonProto::Serialise&lt; std::map&lt; K COMMA_ V &gt; &gt;'],['../structnix_1_1ServeProto_1_1Serialise_3_01std_1_1map_3_01K_01COMMA___01V_01_4_01_4.html',1,'nix::ServeProto::Serialise&lt; std::map&lt; K COMMA_ V &gt; &gt;'],['../structnix_1_1WorkerProto_1_1Serialise_3_01std_1_1map_3_01K_01COMMA___01V_01_4_01_4.html',1,'nix::WorkerProto::Serialise&lt; std::map&lt; K COMMA_ V &gt; &gt;']]],
  ['serialise_3c_20std_3a_3aoptional_3c_20contentaddress_20_3e_20_3e_11',['Serialise&lt; std::optional&lt; ContentAddress &gt; &gt;',['../structnix_1_1CommonProto_1_1Serialise_3_01std_1_1optional_3_01ContentAddress_01_4_01_4.html',1,'nix::CommonProto']]],
  ['serialise_3c_20std_3a_3aoptional_3c_20storepath_20_3e_20_3e_12',['Serialise&lt; std::optional&lt; StorePath &gt; &gt;',['../structnix_1_1CommonProto_1_1Serialise_3_01std_1_1optional_3_01StorePath_01_4_01_4.html',1,'nix::CommonProto']]],
  ['serialise_3c_20std_3a_3aoptional_3c_20trustedflag_20_3e_20_3e_13',['Serialise&lt; std::optional&lt; TrustedFlag &gt; &gt;',['../structnix_1_1WorkerProto_1_1Serialise_3_01std_1_1optional_3_01TrustedFlag_01_4_01_4.html',1,'nix::WorkerProto']]],
  ['serialise_3c_20std_3a_3aset_3c_20t_20_3e_20_3e_14',['Serialise&lt; std::set&lt; T &gt; &gt;',['../structnix_1_1CommonProto_1_1Serialise_3_01std_1_1set_3_01T_01_4_01_4.html',1,'nix::CommonProto::Serialise&lt; std::set&lt; T &gt; &gt;'],['../structnix_1_1ServeProto_1_1Serialise_3_01std_1_1set_3_01T_01_4_01_4.html',1,'nix::ServeProto::Serialise&lt; std::set&lt; T &gt; &gt;'],['../structnix_1_1WorkerProto_1_1Serialise_3_01std_1_1set_3_01T_01_4_01_4.html',1,'nix::WorkerProto::Serialise&lt; std::set&lt; T &gt; &gt;']]],
  ['serialise_3c_20std_3a_3astring_20_3e_15',['Serialise&lt; std::string &gt;',['../structnix_1_1CommonProto_1_1Serialise_3_01std_1_1string_01_4.html',1,'nix::CommonProto']]],
  ['serialise_3c_20std_3a_3atuple_3c_20ts_2e_2e_2e_20_3e_20_3e_16',['Serialise&lt; std::tuple&lt; Ts... &gt; &gt;',['../structnix_1_1CommonProto_1_1Serialise_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html',1,'nix::CommonProto::Serialise&lt; std::tuple&lt; Ts... &gt; &gt;'],['../structnix_1_1ServeProto_1_1Serialise_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html',1,'nix::ServeProto::Serialise&lt; std::tuple&lt; Ts... &gt; &gt;'],['../structnix_1_1WorkerProto_1_1Serialise_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html',1,'nix::WorkerProto::Serialise&lt; std::tuple&lt; Ts... &gt; &gt;']]],
  ['serialise_3c_20std_3a_3avector_3c_20t_20_3e_20_3e_17',['Serialise&lt; std::vector&lt; T &gt; &gt;',['../structnix_1_1CommonProto_1_1Serialise_3_01std_1_1vector_3_01T_01_4_01_4.html',1,'nix::CommonProto::Serialise&lt; std::vector&lt; T &gt; &gt;'],['../structnix_1_1ServeProto_1_1Serialise_3_01std_1_1vector_3_01T_01_4_01_4.html',1,'nix::ServeProto::Serialise&lt; std::vector&lt; T &gt; &gt;'],['../structnix_1_1WorkerProto_1_1Serialise_3_01std_1_1vector_3_01T_01_4_01_4.html',1,'nix::WorkerProto::Serialise&lt; std::vector&lt; T &gt; &gt;']]],
  ['serialise_3c_20storepath_20_3e_18',['Serialise&lt; StorePath &gt;',['../structnix_1_1CommonProto_1_1Serialise_3_01StorePath_01_4.html',1,'nix::CommonProto']]],
  ['serialise_3c_20unkeyedvalidpathinfo_20_3e_19',['Serialise&lt; UnkeyedValidPathInfo &gt;',['../structnix_1_1ServeProto_1_1Serialise_3_01UnkeyedValidPathInfo_01_4.html',1,'nix::ServeProto::Serialise&lt; UnkeyedValidPathInfo &gt;'],['../structnix_1_1WorkerProto_1_1Serialise_3_01UnkeyedValidPathInfo_01_4.html',1,'nix::WorkerProto::Serialise&lt; UnkeyedValidPathInfo &gt;']]],
  ['serialise_3c_20validpathinfo_20_3e_20',['Serialise&lt; ValidPathInfo &gt;',['../structnix_1_1WorkerProto_1_1Serialise_3_01ValidPathInfo_01_4.html',1,'nix::WorkerProto']]],
  ['serializingtransform_21',['SerializingTransform',['../structnix_1_1SerializingTransform.html',1,'nix']]],
  ['serveproto_22',['ServeProto',['../structnix_1_1ServeProto.html',1,'nix']]],
  ['serveprototest_23',['ServeProtoTest',['../structnix_1_1ServeProtoTest.html',1,'nix']]],
  ['setting_24',['Setting',['../classnix_1_1Setting.html',1,'nix']]],
  ['setting_3c_20bool_20_3e_25',['Setting&lt; bool &gt;',['../classnix_1_1Setting.html',1,'nix']]],
  ['setting_3c_20int_20_3e_26',['Setting&lt; int &gt;',['../classnix_1_1Setting.html',1,'nix']]],
  ['setting_3c_20path_20_3e_27',['Setting&lt; Path &gt;',['../classnix_1_1Setting.html',1,'nix']]],
  ['setting_3c_20std_3a_3aoptional_3c_20uint16_5ft_20_3e_20_3e_28',['Setting&lt; std::optional&lt; uint16_t &gt; &gt;',['../classnix_1_1Setting.html',1,'nix']]],
  ['setting_3c_20std_3a_3astring_20_3e_29',['Setting&lt; std::string &gt;',['../classnix_1_1Setting.html',1,'nix']]],
  ['setting_3c_20stringset_20_3e_30',['Setting&lt; StringSet &gt;',['../classnix_1_1Setting.html',1,'nix']]],
  ['setting_3c_20unsigned_20int_20_3e_31',['Setting&lt; unsigned int &gt;',['../classnix_1_1Setting.html',1,'nix']]],
  ['settingdata_32',['SettingData',['../structnix_1_1Config_1_1SettingData.html',1,'nix::Config']]],
  ['settinginfo_33',['SettingInfo',['../structnix_1_1AbstractConfig_1_1SettingInfo.html',1,'nix::AbstractConfig']]],
  ['settings_34',['Settings',['../classnix_1_1Settings.html',1,'nix']]],
  ['shared_5ffd_35',['shared_fd',['../structnix_1_1AsyncFdInputStream_1_1shared__fd.html',1,'nix::AsyncFdInputStream']]],
  ['shlexerror_36',['ShlexError',['../classnix_1_1ShlexError.html',1,'nix']]],
  ['simplelogger_37',['SimpleLogger',['../classnix_1_1SimpleLogger.html',1,'nix']]],
  ['simplepattern_38',['SimplePattern',['../structnix_1_1SimplePattern.html',1,'nix']]],
  ['simpleuserlock_39',['SimpleUserLock',['../structnix_1_1SimpleUserLock.html',1,'nix']]],
  ['singlebuiltpath_40',['SingleBuiltPath',['../structnix_1_1SingleBuiltPath.html',1,'nix']]],
  ['singlebuiltpathbuilt_41',['SingleBuiltPathBuilt',['../structnix_1_1SingleBuiltPathBuilt.html',1,'nix']]],
  ['singlederivedpath_42',['SingleDerivedPath',['../structnix_1_1SingleDerivedPath.html',1,'nix']]],
  ['singlederivedpathbuilt_43',['SingleDerivedPathBuilt',['../structnix_1_1SingleDerivedPathBuilt.html',1,'nix']]],
  ['sink_44',['Sink',['../structnix_1_1Sink.html',1,'nix']]],
  ['sizedsource_45',['SizedSource',['../structnix_1_1SizedSource.html',1,'nix']]],
  ['source_46',['Source',['../structnix_1_1Source.html',1,'nix']]],
  ['sourceexprcommand_47',['SourceExprCommand',['../structnix_1_1SourceExprCommand.html',1,'nix']]],
  ['sourcehutinputscheme_48',['SourceHutInputScheme',['../structnix_1_1fetchers_1_1SourceHutInputScheme.html',1,'nix::fetchers']]],
  ['sourcepath_49',['SourcePath',['../structnix_1_1SourcePath.html',1,'nix']]],
  ['sqlite_50',['SQLite',['../classnix_1_1SQLite.html',1,'nix']]],
  ['sqliteerror_51',['SQLiteError',['../structnix_1_1SQLiteError.html',1,'nix']]],
  ['sqlitestmt_52',['SQLiteStmt',['../classnix_1_1SQLiteStmt.html',1,'nix']]],
  ['sqlitetxn_53',['SQLiteTxn',['../classnix_1_1SQLiteTxn.html',1,'nix']]],
  ['sshmaster_54',['SSHMaster',['../classnix_1_1SSHMaster.html',1,'nix']]],
  ['sshstore_55',['SSHStore',['../classnix_1_1SSHStore.html',1,'nix']]],
  ['sshstoreconfig_56',['SSHStoreConfig',['../structnix_1_1SSHStoreConfig.html',1,'nix']]],
  ['stat_57',['Stat',['../structnix_1_1FSAccessor_1_1Stat.html',1,'nix::FSAccessor::Stat'],['../structnix_1_1InputAccessor_1_1Stat.html',1,'nix::InputAccessor::Stat']]],
  ['state_58',['State',['../structnix_1_1curlFileTransfer_1_1State.html',1,'nix::curlFileTransfer::State'],['../structnix_1_1daemon_1_1TunnelLogger_1_1State.html',1,'nix::daemon::TunnelLogger::State'],['../structnix_1_1eval__cache_1_1AttrDb_1_1State.html',1,'nix::eval_cache::AttrDb::State'],['../structnix_1_1fetchers_1_1CacheImpl_1_1State.html',1,'nix::fetchers::CacheImpl::State'],['../structnix_1_1NarInfoDiskCacheImpl_1_1State.html',1,'nix::NarInfoDiskCacheImpl::State'],['../structnix_1_1ProgressBar_1_1State.html',1,'nix::ProgressBar::State'],['../structnix_1_1State.html',1,'nix::State'],['../structnix_1_1Store_1_1State.html',1,'nix::Store::State']]],
  ['staticenv_59',['StaticEnv',['../structnix_1_1StaticEnv.html',1,'nix']]],
  ['staticsymbols_60',['StaticSymbols',['../structnix_1_1StaticSymbols.html',1,'nix']]],
  ['statistics_61',['Statistics',['../structnix_1_1EvalMemory_1_1Statistics.html',1,'nix::EvalMemory']]],
  ['stats_62',['Stats',['../structnix_1_1S3BinaryCacheStore_1_1Stats.html',1,'nix::S3BinaryCacheStore::Stats'],['../structnix_1_1Store_1_1Stats.html',1,'nix::Store::Stats&lt; Wrapper &gt;']]],
  ['stats_3c_20std_3a_3aatomic_20_3e_63',['Stats&lt; std::atomic &gt;',['../structnix_1_1Store_1_1Stats.html',1,'nix::Store']]],
  ['stdin_64',['Stdin',['../structnix_1_1Pos_1_1Stdin.html',1,'nix::Pos']]],
  ['stmts_65',['Stmts',['../structnix_1_1LocalStore_1_1DBState_1_1Stmts.html',1,'nix::LocalStore::DBState']]],
  ['store_66',['Store',['../classnix_1_1Store.html',1,'nix']]],
  ['storecommand_67',['StoreCommand',['../structnix_1_1StoreCommand.html',1,'nix']]],
  ['storeconfig_68',['StoreConfig',['../structnix_1_1StoreConfig.html',1,'nix']]],
  ['storefactory_69',['StoreFactory',['../structnix_1_1StoreFactory.html',1,'nix']]],
  ['storeimplementations_70',['StoreImplementations',['../structnix_1_1StoreImplementations.html',1,'nix']]],
  ['storepath_71',['StorePath',['../classnix_1_1StorePath.html',1,'nix']]],
  ['storepathcommand_72',['StorePathCommand',['../structnix_1_1StorePathCommand.html',1,'nix']]],
  ['storepathscommand_73',['StorePathsCommand',['../structnix_1_1StorePathsCommand.html',1,'nix']]],
  ['storepathtest_74',['StorePathTest',['../classnix_1_1StorePathTest.html',1,'nix']]],
  ['storepathwithoutputs_75',['StorePathWithOutputs',['../structnix_1_1StorePathWithOutputs.html',1,'nix']]],
  ['storereferences_76',['StoreReferences',['../structnix_1_1StoreReferences.html',1,'nix']]],
  ['streamtosourceadapter_77',['StreamToSourceAdapter',['../structnix_1_1StreamToSourceAdapter.html',1,'nix']]],
  ['string_78',['String',['../structnix_1_1BuildEnvironment_1_1String.html',1,'nix::BuildEnvironment::String'],['../structnix_1_1Pos_1_1String.html',1,'nix::Pos::String']]],
  ['string_5ft_79',['string_t',['../structnix_1_1NewValueAs_1_1string__t.html',1,'nix::NewValueAs']]],
  ['stringprintingtests_80',['StringPrintingTests',['../structnix_1_1StringPrintingTests.html',1,'nix']]],
  ['stringsink_81',['StringSink',['../structnix_1_1StringSink.html',1,'nix']]],
  ['stringsource_82',['StringSource',['../structnix_1_1StringSource.html',1,'nix']]],
  ['substitutablepathinfo_83',['SubstitutablePathInfo',['../structnix_1_1SubstitutablePathInfo.html',1,'nix']]],
  ['suggestion_84',['Suggestion',['../classnix_1_1Suggestion.html',1,'nix']]],
  ['suggestions_85',['Suggestions',['../classnix_1_1Suggestions.html',1,'nix']]],
  ['symbol_86',['Symbol',['../classnix_1_1Symbol.html',1,'nix']]],
  ['symbolstr_87',['SymbolStr',['../classnix_1_1SymbolStr.html',1,'nix']]],
  ['symboltable_88',['SymbolTable',['../classnix_1_1SymbolTable.html',1,'nix']]],
  ['symlink_89',['Symlink',['../structnix_1_1nar_1_1Symlink.html',1,'nix::nar::Symlink'],['../structnix_1_1nar__index_1_1Symlink.html',1,'nix::nar_index::Symlink'],['../structnix_1_1PrefilteredDump_1_1Symlink.html',1,'nix::PrefilteredDump::Symlink']]],
  ['sync_90',['Sync',['../classnix_1_1Sync.html',1,'nix']]],
  ['sync_3c_20dbstate_2c_20asyncmutex_20_3e_91',['Sync&lt; DBState, AsyncMutex &gt;',['../classnix_1_1Sync.html',1,'nix']]],
  ['sync_3c_20gcstate_20_3e_92',['Sync&lt; GCState &gt;',['../classnix_1_1Sync.html',1,'nix']]],
  ['sync_3c_20nix_3a_3aautoclosefd_20_3e_93',['Sync&lt; nix::AutoCloseFD &gt;',['../classnix_1_1Sync.html',1,'nix']]],
  ['sync_3c_20nix_3a_3acurlfiletransfer_3a_3astate_20_3e_94',['Sync&lt; nix::curlFileTransfer::State &gt;',['../classnix_1_1Sync.html',1,'nix']]],
  ['sync_3c_20nix_3a_3acurlfiletransfer_3a_3atransferitem_3a_3adownloadstate_20_3e_95',['Sync&lt; nix::curlFileTransfer::TransferItem::DownloadState &gt;',['../classnix_1_1Sync.html',1,'nix']]],
  ['sync_3c_20nix_3a_3adaemon_3a_3atunnellogger_3a_3astate_20_3e_96',['Sync&lt; nix::daemon::TunnelLogger::State &gt;',['../classnix_1_1Sync.html',1,'nix']]],
  ['sync_3c_20nix_3a_3afetchers_3a_3acacheimpl_3a_3astate_20_3e_97',['Sync&lt; nix::fetchers::CacheImpl::State &gt;',['../classnix_1_1Sync.html',1,'nix']]],
  ['sync_3c_20nix_3a_3anarinfodiskcacheimpl_3a_3astate_20_3e_98',['Sync&lt; nix::NarInfoDiskCacheImpl::State &gt;',['../classnix_1_1Sync.html',1,'nix']]],
  ['sync_3c_20nix_3a_3aprogressbar_3a_3astate_20_3e_99',['Sync&lt; nix::ProgressBar::State &gt;',['../classnix_1_1Sync.html',1,'nix']]],
  ['sync_3c_20nix_3a_3astore_3a_3astate_2c_20asyncmutex_20_3e_100',['Sync&lt; nix::Store::State, AsyncMutex &gt;',['../classnix_1_1Sync.html',1,'nix']]],
  ['sync_3c_20nix_3a_3athreadpool_20_3e_101',['Sync&lt; nix::ThreadPool &gt;',['../classnix_1_1Sync.html',1,'nix']]],
  ['sync_3c_20shared_20_3e_102',['Sync&lt; Shared &gt;',['../classnix_1_1Sync.html',1,'nix']]],
  ['sync_3c_20state_20_3e_103',['Sync&lt; State &gt;',['../classnix_1_1Sync.html',1,'nix']]],
  ['sync_3c_20std_3a_3amap_3c_20uint32_5ft_2c_20lines_20_3e_20_3e_104',['Sync&lt; std::map&lt; uint32_t, Lines &gt; &gt;',['../classnix_1_1Sync.html',1,'nix']]],
  ['sync_3c_20t_2c_20asyncmutex_20_3e_105',['Sync&lt; T, AsyncMutex &gt;',['../classnix_1_1Sync_3_01T_00_01AsyncMutex_01_4.html',1,'nix']]],
  ['sync_3c_20t_2c_20std_3a_3amutex_20_3e_106',['Sync&lt; T, std::mutex &gt;',['../classnix_1_1Sync.html',1,'nix']]],
  ['syserror_107',['SysError',['../classnix_1_1SysError.html',1,'nix']]]
];
